version: '3.1'

services:
  db:
    image: mongo:8.0.0-rc13-jammy
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
